apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: {{tenant_name}}
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYj5zcnY6Ly9lUmFsZjphMXhHZXpZUkQ3d2FzSzgyfHZlRDIvMTI9YTRIZw==
  REDIS_HOST: MTEwLjIzOC43OS4xODE=
  REDIS_PORT: NjM3OQ==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: {{tenant_name}}
data:
  REDIS_DB: "0"
  REDIS_SSL: "false"
  REDIS_TIMEOUT: "5"
  REDIS_MAX_RETRIES: "3"
  REDIS_RETRY_DELAY: "1"
  TOKEN_VERIFICATION_URL: "http://auth-service:3000/auth/verify"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: {{tenant_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      imagePullSecrets:
        - name: default-secret    
      containers:
      - name: inventory-service
        image: swr.af-south-1.myhuaweicloud.com/ralf/inventory-api:efd2af4df959640451a8c4c47430a8ee9211dc3e
        ports:
        - containerPort: 3001
          envFrom:
            - secretRef:
                name: auth-service-secrets
                               
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{tenant_name}}
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 3001       
      targetPort: 3001     
  type: ClusterIP         